#!/bin/bash -l
# 2_quality_filter.job

### Queuing variables
#PBS -N 
#PBS -d 
#PBS -q fatnodes

#PBS -k oe
#PBS -m ae
#PBS -M 

### Use the script to quality filter assembled paired-end illumina 16S sequences. 

### To run job enter:
# qsub 2_quality_filter.job

### Auxillary scripts and programs
# fastx_toolkit/0.0.13

### Load Modules
module load fastx_toolkit/0.0.13

### Environment variables ###
rawDir=`pwd`
scriptsDir=`find $HOME -path "*/Process_16S/Support_scripts"`
today=(`date`)
runName=`echo "process_16S_${today[2]}${today[1]}${today[5]}"`

### Quality filtering variables (fastq_quality_filter)
qual_min=20
qual_pct=95
qual_outDir=02_Filtered_q${qual_min}p${qual_pct}

##################################################################################

### Quality filtering (fastq_quality_filter)
mkdir $rawDir/$qual_outDir
for fq in $flash_outDir/*fastq; do 
	name=`echo $fq | cut -d '/' -f 2 | rev | cut -d '.' -f 2- | rev`
	fastq_quality_filter -q $qual_min -p $qual_pct -i $fq -o $qual_outDir/$name.filt.fastq -Q 33
done
echo "fastq_quality_filter -q $qual_min -p $qual_pct -i {fq} -o $qual_outDir/{name}.filt.fastq -Q 33" >> $rawDir/$runName.log
