#!/bin/bash -l
# 9_build_tree_assign_taxa.job

### Queuing variables
#PBS -N 
#PBS -d 
#PBS -q fatnodes

#PBS -k oe
#PBS -m ae
#PBS -M 

### Use the script to make a phylogeny from OTU seed sequences and assign taxonomy.

### To run job enter:
# qsub 9_build_tree_assign_taxa.job

### Auxillary scripts and programs
# fasttree/2.1.4
# RDPTools/140616
# rdp_tax2phyloseq_tax_nosupp.pl

rawDir=`pwd`
# scriptsDir=`find $HOME -path "*/Process_16S/Support_scripts"`
today=(`date`)
runName=`echo "process_16S_${today[2]}${today[1]}${today[5]}"`
final_outDir=00_Final_output

### Load Modules
module load fasttree/2.1.4
module load RDPTools/140616

### FastTree variables
fasttree_log=$rawDir/${runName}_fasttree.log

##################################################################################

### Build tree (FastTree)
cd $final_outDir
FastTree -nt -nosupport -quote -gtr -gamma -log $fasttree_log all_smpls.otu_seqs.aln.fasta > all_smpls.otus.tree
echo -e "FastTree -nt -nosupport -quote -gtr -gamma -log $fasttree_log all_smpls.otu_seqs.aln.fasta > all_smpls.otus.tree\n" >> $rawDir/$runName.log

### Taxon assignment (RDP classifier)
java -Xmx1g -jar /usr/local/packages/RDPTools/140616/classifier.jar classify all_smpls.otu_seqs.aln.fasta -o all_smpls.taxa_tbl.rdp.txt
echo -e "java -Xmx1g -jar /usr/local/packages/RDPTools/classifier.jar classify all_smpls.otu_seqs.aln.fasta -o all_smpls.taxa_tbl.rdp.txt\n" >> $rawDir/$runName.log

$scriptsDir/rdp_tax2phyloseq_tax_nosupp.pl -i all_smpls.taxa_tbl.rdp.txt
mv all_smpls.taxa_tbl.rdp.phyloseq.txt all_smpls.taxa_tbl.phyloseq.txt

cd $rawDir
