#!/bin/bash -l
# 4_dereplicate.job

### Queuing variables
# (The d flag is always the raw reads directory)
#PBS -N 
#PBS -d 
#PBS -q fatnodes

#PBS -k oe
#PBS -m ae
#PBS -M 

### Use the script to dereplicate 16S sequences contained in a single file.

### To run job enter:
# qsub 4_dereplicate.job (Run anywhere)
#		-OR-
# PATH/TO/Process_16S/Modular_scripts/4_dereplicate.job (Run within raw reads directory)

### Auxillary scripts and programs
# uniq_16S.pl

###### Which clustering tool would you like to use? ######
clusterTool=usearch # this option is more for the clustering script, but is required here for proper data handling

###### Include singletons by matching them back to clusters formed without them ("yes" or "no")? ######
inclSngls=no # this option is more for the clustering script, but is required here for proper data handling

rawDir=`pwd`
scriptsDir=`find $HOME -path "*/Process_16S/Support_scripts"`
today=(`date`)
runName=`echo "process_16S_${today[2]}${today[1]}${today[5]}"`
echo "clusterTool=$clusterTool" >> $rawDir/$runName.log
echo "inclSngls=$inclSngls" >> $rawDir/$runName.log

### Concatenating variables (cat)
concatName=all_smpls.joined.filt

### Dereplicate reads variables (uniq_16S.pl)
uniq_outDir=03_UniqSeq_files
uniq_keep=2 # mininum number of identical sequences to keep unique read
echo "uniq_keep=$uniq_keep" >> $rawDir/$runName.log
gt=`expr $uniq_keep - 1` # for file naming purposes

##################################################################################

### Dereplicate unique reads (uniq_16S.pl) &
### Drop unique reads with abundance lowere than $uniq_keep
cd $rawDir/$uniq_outDir

if [ $clusterTool == 'usearch' ]; then 
	if [ $inclSngls == 'yes' ]; then 
		$scriptsDir/uniq_16S.pl -s -u -i $concatName.fasta -k $uniq_keep
		echo -e "$scriptsDir/uniq_16S.pl -s -u -i $concatName.fasta -k $uniq_keep\n" >> $rawDir/$runName.log
	else 
		$scriptsDir/uniq_16S.pl -s -i $concatName.fasta -k $uniq_keep
		echo -e "$scriptsDir/uniq_16S.pl -s -i $concatName.fasta -k $uniq_keep\n" >> $rawDir/$runName.log
	fi
else 
	if [ $inclSngls == 'yes' ]; then 
		$scriptsDir/uniq_16S.pl -u -i $concatName.fasta -k $uniq_keep # difference is -s flag not present, which adds ;size= for usearch to headers
		echo -e "$scriptsDir/uniq_16S.pl -u -i $concatName.fasta -k $uniq_keep\n" >> $rawDir/$runName.log
	else 
		$scriptsDir/uniq_16S.pl -i $concatName.fasta -k $uniq_keep # difference is -s flag not present, which adds ;size= for usearch to headers
		echo -e "$scriptsDir/uniq_16S.pl -i $concatName.fasta -k $uniq_keep\n" >> $rawDir/$runName.log
	fi
fi
overThreshName=`echo *gt*.fasta | rev | cut -d '.' -f 2- | rev`
if [ $inclSngls == 'yes' ]; then 
	underThreshName=`echo *lte*.fasta | rev | cut -d '.' -f 2- | rev`
fi

cd $rawDir
